services:
  payment-service:
    image: openjdk:22-jdk-oracle
    container_name: paymentimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    env_file:
      - .env
    depends_on:
      - payment-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/PaymentService-v0.1.8.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  payment-db:
    image: mongo:latest
    container_name: paymentdb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_payment:/etc/mongo
      - mongo_payment_data:/data/db
      - mongo_payment_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:

volumes:
  mongo_payment:
  mongo_payment_data:
  mongo_payment_config:
