services:
  request-service:
    image: openjdk:22-jdk-oracle
    container_name: requestimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    env_file:
      - .env
    depends_on:
      - request-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/RequestManagementService-v0.0.1.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  request-db:
    image: mongo:latest
    container_name: requestdb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_request:/etc/mongo
      - mongo_request_data:/data/db
      - mongo_request_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:

volumes:
  mongo_request:
  mongo_request_data:
  mongo_request_config:
